### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by Vasiliy566** [aswinkumarks/Alpha-Code#12]
is there any timeout on code execution?
as example - run 
```
while True:
    print(1)
```
 on any contest and running progress will not stop ever 
![image](https://user-images.githubusercontent.com/28749508/102019184-093dfe80-3d83-11eb-9c42-c9c5a5cdb251.png)

**Comment by krishnabhat3383** [comment]
check the Code run server/container.py. We have used the ```timeout``` command here to achieve this. this was tested and was working when we first implemented it way back when. but please do reply to this issue if you are finding any difficulties.

**Comment by krishnabhat3383** [comment]
just found out that the implementation done was overridden at some point for adding new features, and as of yet has not been reintegrated yet. you are welcome to help us out, or wait while we are working on it. we'll be done in a jiffy.

**Comment by Vasiliy566** [comment]
@RoranBlackfire just started to view your project, so will help with it recent

**Comment by aswinkumarks** [comment]
Time out is already implemented. Check the file _Code Run Server/container.py_ for more info.
